[config]
default_to_workspace = false

[env]
WEB = "/web/mindustry-mods"
SYS = "/etc/systemd/system"
SERVICES = "mindustry-mods-web" # mindustry-mods-script"

[tasks.release]
dependencies = [ "wasm-build" ]

[tasks.wasm-build]
script = "wasm-pack build frontend --target web"
