[config]
default_to_workspace = false

[env]
OUT = "dist"

[tasks.release]
dependencies = [ "wasm-build", "copy-files" ]

[tasks.copy-files]
script_runner = "@shell"
script = [
    "cp frontend/pkg ${OUT} -rf",
    "cp frontend/css ${OUT} -fr",
    "cp frontend/index.html ${OUT} -f",
    "cp frontend/images ${OUT} -fr"
]

[tasks.wasm-build]
script_runner = "@shell"
script = [ "wasm-pack build frontend --target web" ]
